//Add this to your CLI Config  file. Populate it with the codes from the config tab of the google sheet, or simply copy in the config code generated by the google sheet.

config.gforms = {
  enabled: true,
  botTag: '', //Add a custom tag here, i.e. 'Paper' or 'Live'
  //Form ID - the long code from the form url
  formID: '',
  //Form question ID's
  tag: '',
  exchange: '',
  currency: '',
  asset: '',
  action: '',
  assetCount: '',
  price: '',
  currencyCount: '',
  balance: '',
  advicePrice: '',
  timeTaken: ''
};
